// HTML Parser - Preserves external HTML structure
// For external HTML: Keep as raw HTML blocks to preserve typography/layout
// For editor-generated HTML: Parse layout metadata and restore structure

import { sanitizeHTML } from './Sanitizer';
import { v4 as uuidv4 } from 'uuid';
import type { EditorBlock, EditorSection } from '../editorConfig';

export interface ParsedDocument {
  sections: EditorSection[];
  rawHTML: string;
  isEditorGenerated: boolean;
}

// Metadata marker for editor-generated HTML
const EDITOR_METADATA_ATTR = 'data-editor-layout';
const EDITOR_SECTION_ATTR = 'data-section';
const EDITOR_COLUMN_ATTR = 'data-column';

/**
 * Parse HTML and convert to editor structure
 * - If HTML was generated by this editor, restore exact layout
 * - If external HTML, preserve as raw blocks to maintain typography
 */
export function parseHTML(html: string): ParsedDocument {
  const sanitized = sanitizeHTML(html);
  const parser = new DOMParser();
  const doc = parser.parseFromString(sanitized, 'text/html');
  
  // Check if this HTML was generated by our editor
  const isEditorGenerated = doc.querySelector(`[${EDITOR_METADATA_ATTR}]`) !== null;
  
  if (isEditorGenerated) {
    return parseEditorGeneratedHTML(doc, sanitized);
  } else {
    return parseExternalHTML(doc, sanitized);
  }
}

/**
 * Parse HTML that was generated by this editor
 * Restores exact layout from metadata
 */
function parseEditorGeneratedHTML(doc: Document, rawHTML: string): ParsedDocument {
  const sections: EditorSection[] = [];
  
  // Find all sections with our metadata
  const sectionElements = doc.querySelectorAll(`[${EDITOR_SECTION_ATTR}]`);
  
  sectionElements.forEach((sectionEl) => {
    const columnsAttr = sectionEl.getAttribute(EDITOR_METADATA_ATTR);
    const columns = (parseInt(columnsAttr || '1') || 1) as 1 | 2 | 3;
    
    const section: EditorSection = {
      id: uuidv4(),
      columns,
      blocks: Array(columns).fill(null).map(() => []),
    };
    
    // Find column containers
    const columnContainers = sectionEl.querySelectorAll(`[${EDITOR_COLUMN_ATTR}]`);
    
    if (columnContainers.length > 0) {
      columnContainers.forEach((colEl, colIndex) => {
        if (colIndex < columns) {
          // Parse blocks within this column
          const blocks = parseColumnBlocks(colEl as HTMLElement);
          section.blocks[colIndex] = blocks;
        }
      });
    } else {
      // Single column - parse direct children
      const blocks = parseColumnBlocks(sectionEl as HTMLElement);
      section.blocks[0] = blocks;
    }
    
    sections.push(section);
  });
  
  // If no sections found, fallback to external parsing
  if (sections.length === 0) {
    return parseExternalHTML(doc.defaultView?.document || doc, rawHTML);
  }
  
  return {
    sections,
    rawHTML,
    isEditorGenerated: true,
  };
}

/**
 * Parse external HTML (not generated by this editor)
 * Preserves as raw HTML blocks to maintain original typography
 */
function parseExternalHTML(doc: Document, rawHTML: string): ParsedDocument {
  const body = doc.body;
  
  // Extract style tags to preserve CSS
  const styles: string[] = [];
  doc.querySelectorAll('style').forEach(style => {
    styles.push(style.innerHTML);
  });
  const originalStyles = styles.join('\n');
  
  // Group content into logical sections based on structure
  const sections: EditorSection[] = [];
  const blocks: EditorBlock[] = [];
  
  // Process top-level children
  for (let i = 0; i < body.childNodes.length; i++) {
    const node = body.childNodes[i];
    
    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent?.trim();
      if (text) {
        blocks.push(createRawHTMLBlock(`<p>${escapeHTML(text)}</p>`, originalStyles));
      }
      continue;
    }
    
    if (node.nodeType !== Node.ELEMENT_NODE) continue;
    
    const element = node as HTMLElement;
    const tagName = element.tagName.toLowerCase();
    
    // Skip empty elements
    if (!element.innerHTML.trim() && !['hr', 'br', 'img', 'input'].includes(tagName)) {
      continue;
    }
    
    // Create block based on element type
    blocks.push(createRawHTMLBlock(element.outerHTML, originalStyles));
  }
  
  // Create single section with all blocks
  if (blocks.length > 0) {
    sections.push({
      id: uuidv4(),
      columns: 1,
      blocks: [blocks],
    });
  }
  
  return {
    sections,
    rawHTML,
    isEditorGenerated: false,
  };
}

/**
 * Parse blocks within a column container
 */
function parseColumnBlocks(container: HTMLElement): EditorBlock[] {
  const blocks: EditorBlock[] = [];
  
  for (let i = 0; i < container.children.length; i++) {
    const element = container.children[i] as HTMLElement;
    const blockType = element.getAttribute('data-block-type');
    
    if (blockType === 'raw-html' || !blockType) {
      // Preserve as raw HTML
      blocks.push(createRawHTMLBlock(element.innerHTML, ''));
    } else {
      // Try to restore specific block type
      const block = restoreTypedBlock(element, blockType);
      if (block) {
        blocks.push(block);
      }
    }
  }
  
  return blocks;
}

/**
 * Create a raw HTML block that preserves original structure
 */
function createRawHTMLBlock(html: string, originalStyles: string): EditorBlock {
  return {
    id: uuidv4(),
    type: 'raw-html' as const,
    htmlContent: html,
    originalStyles,
    width: 100,
    marginTop: 0,
    marginBottom: 8,
    paddingX: 0,
    paddingY: 0,
    locked: false,
  };
}

/**
 * Restore a typed block from metadata
 */
function restoreTypedBlock(element: HTMLElement, blockType: string): EditorBlock | null {
  const baseProps = {
    id: uuidv4(),
    width: 100,
    marginTop: 0,
    marginBottom: 8,
    paddingX: 0,
    paddingY: 0,
    locked: false,
  };
  
  switch (blockType) {
    case 'heading':
      return {
        ...baseProps,
        type: 'heading' as const,
        content: element.textContent || '',
        htmlContent: element.innerHTML,
        level: (element.getAttribute('data-level') || 'h2') as 'h1' | 'h2' | 'h3' | 'h4',
        fontSize: parseInt(element.getAttribute('data-font-size') || '24'),
        fontWeight: parseInt(element.getAttribute('data-font-weight') || '600'),
        textAlign: element.getAttribute('data-align') || 'left',
        lineHeight: parseFloat(element.getAttribute('data-line-height') || '1.3'),
        color: element.getAttribute('data-color') || '',
      };
      
    case 'paragraph':
      return {
        ...baseProps,
        type: 'paragraph' as const,
        content: element.textContent || '',
        htmlContent: element.innerHTML,
        fontSize: parseInt(element.getAttribute('data-font-size') || '14'),
        fontWeight: parseInt(element.getAttribute('data-font-weight') || '400'),
        textAlign: element.getAttribute('data-align') || 'left',
        lineHeight: parseFloat(element.getAttribute('data-line-height') || '1.6'),
        color: element.getAttribute('data-color') || '',
      };
      
    default:
      // Unknown type - preserve as raw HTML
      return createRawHTMLBlock(element.outerHTML, '');
  }
}

function escapeHTML(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Legacy export for compatibility
export type { EditorBlock as ParsedBlock };
